### PR TITLE
feat: hide cursor, use vim.fn.getmousepos

### PR DESCRIPTION
**Pull request by willothy**
This PR allows hiding the mouse cursor in the menu, and updates the way the mouse position is fetched to use `vim.fn.getmousepos`, which is less hacky than moving the cursor on mouse move.

todo: make hiding the cursor optional

### CODE REVIEW

**Comment by notomo** [comment]
Thanks!
I would like to confirm the followings.

1. Does this works?
In my environment, the cursor is visible.
image


2. Does winhighlight resolves the issue?
📝 Example
```lua
vim.api.nvim_create_autocmd({ "FileType" }, {
  group = vim.api.nvim_create_augroup("piemenu_highlight", {}),
  pattern = { "piemenu" },
  callback = function()
    vim.wo.winhighlight = "Cursor:NONE"
  end,
})
```

**Comment by willothy** [comment]
Interesting, I'll have to look into this. I use noice.nvim which draws its own cursor, so I'll have to disable it and check. I'll mark this as a draft for now and update when it works haha :)

Edit: should work now

**Comment by willothy** [comment]
And as for winhighlight, that doesn't resolve it as hiding the cursor can be tricky. Anyways, using vim.fn.getmousepos makes more sense than using the background's cursor imo.

**Comment by notomo** [comment]
Using getmousepos() is good! (though should fix some tests)

But I don't want to modify global option (and highlight) as plugin function. Sorry.

Instead, you can hide cursor and restore it by user side autocmd.

```lua
vim.api.nvim_set_hl(0, "InvisibleCursor", { bg = 0, blend = 100 })
vim.api.nvim_create_autocmd({ "FileType" }, {
  group = vim.api.nvim_create_augroup("piemenu_hide_cursor", {}),
  pattern = { "piemenu" },
  callback = function()
    local original = vim.api.nvim_get_hl(0, { name = "Cursor" })
    vim.api.nvim_set_hl(0, "Cursor", { link = "InvisibleCursor" })
    vim.api.nvim_create_autocmd({ "BufWipeout" }, {
      buffer = 0,
      once = true,
      callback = function()
        vim.api.nvim_set_hl(0, "Cursor", original)
      end,
    })
  end,
})
```

**Comment by willothy** [comment]
That's fair, no worries! Would you be open to a PR just including the getmousepos() changes?

**Comment by notomo** [comment]
Thanks.
But I'll fix to use getmousepos() and consider the way of the test by myself.

**Comment by willothy** [comment]
Sounds good, I'll switch back to using the main repo when that's done :)

By the way, you may want to add a stylua config file so it's easier for others to keep the code in your preferred style.

**Comment by notomo** [comment]
> use getmousepos()

implemented notomo/piemenu.nvim@3b0e3ca

**Pull request closed without merging**
